# <font color=#225e71>Support Vector Machine </font>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

from sklearn.svm import LinearSVR
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV

In [2]:
data = pd.read_csv(r"C:\\Users\\Giorgis\\Desktop\\Projects\\ADTA coursework\\partI\\Census.csv")
data.head(1)

Person ID     Region Residence Type  Family Composition  Population Base  \
0    7394816  E12000001              H                   2                1   

   Sex  Age  Marital Status  Student  Country of Birth  Health  Ethnic Group  \
0    2    6               2        2                 1       2             1   

   Religion  Economic Activity  Occupation  Industry  Hours worked per week  \
0         2                  5           8         2                     -9   

   No of hours  Approximated Social Grade  
0          NaN                          4

In [3]:
data1 = data.drop(['Region', 'Residence Type', 'No of hours', 'Person ID'], axis=1)

df = data1
df

Family Composition  Population Base  Sex  Age  Marital Status  \
0                        2                1    2    6               2   
1                        3                1    2    1               1   
2                        2                1    1    7               2   
3                        1                1    2    6               4   
4                        2                1    1    1               1   
...                    ...              ...  ...  ...             ...   
569735                  -9                1    1    2               1   
569736                  -9                1    1    3               1   
569737                  -9                1    2    5               2   
569738                   2                1    1    6               2   
569739                   1                1    1    5               4   

        Student  Country of Birth  Health  Ethnic Group  Religion  \
0             2                 1       2             1         2   
1             2                 1       2             1         1   
2             2                 1       1             1         2   
3             2                 1       3             1         2   
4             1                 1       1             1         1   
...         ...               ...     ...           ...       ...   
569735        2                 2       1             1         2   
569736        2                 2       2             2         1   
569737        2                 1       1             1         2   
569738        2                 1       3             1         1   
569739        2                 1       2             1         1   

        Economic Activity  Occupation  Industry  Hours worked per week  \
0                       5           8         2                     -9   
1                      -9          -9        -9                     -9   
2                       5           8         2                     -9   
3                       5           9         5                     -9   
4                      -9          -9        -9                     -9   
...                   ...         ...       ...                    ...   
569735                  1           3         9                      4   
569736                  1           1         5                      4   
569737                  2           1         8                      4   
569738                  1           6        10                      4   
569739                  1           5         2                      4   

        Approximated Social Grade  
0                               4  
1                              -9  
2                               2  
3                               4  
4                              -9  
...                           ...  
569735                         -9  
569736                         -9  
569737                         -9  
569738                          3  
569739                          3  

[569740 rows x 15 columns]

#### <font color=#225e71> Excluding the _-9_ value of the __Approximated Social Grade__ attribute </font>

In [4]:
df_exclude = df[(df['Approximated Social Grade'] == -9)]

df = df.drop(df_exclude.index)
df.head(0)

Empty DataFrame
Columns: [Family Composition, Population Base, Sex, Age, Marital Status, Student, Country of Birth, Health, Ethnic Group, Religion, Economic Activity, Occupation, Industry, Hours worked per week, Approximated Social Grade]
Index: []

In [5]:
X = df.drop('Approximated Social Grade', axis=1)
y = df['Approximated Social Grade']


In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [7]:
sc = StandardScaler()
sc.fit(X_train)
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)

#### <font color=#225e71> Creating a dictionary with the multiple values of _C_ and _gama_  </font>

In [8]:
param_grid = {'C': [0.1, 1],
              'gamma': [1, 0.1]}

In [51]:
grid = GridSearchCV(SVC(), param_grid, verbose=3)

In [52]:
grid.fit(X_train, y_train)

Fitting 5 folds for each of 4 candidates, totalling 20 fits
[CV] C=0.1, gamma=1 ..................................................


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


[CV] ...................... C=0.1, gamma=1, score=0.568, total= 4.3min
[CV] C=0.1, gamma=1 ..................................................


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:  4.3min remaining:    0.0s


[CV] ...................... C=0.1, gamma=1, score=0.571, total= 4.8min
[CV] C=0.1, gamma=1 ..................................................


[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:  9.1min remaining:    0.0s


[CV] ...................... C=0.1, gamma=1, score=0.569, total= 4.7min
[CV] C=0.1, gamma=1 ..................................................
[CV] ...................... C=0.1, gamma=1, score=0.567, total= 4.5min
[CV] C=0.1, gamma=1 ..................................................
[CV] ...................... C=0.1, gamma=1, score=0.572, total= 4.5min
[CV] C=0.1, gamma=0.1 ................................................
[CV] .................... C=0.1, gamma=0.1, score=0.664, total= 1.1min
[CV] C=0.1, gamma=0.1 ................................................
[CV] .................... C=0.1, gamma=0.1, score=0.656, total= 1.1min
[CV] C=0.1, gamma=0.1 ................................................
[CV] .................... C=0.1, gamma=0.1, score=0.664, total= 1.1min
[CV] C=0.1, gamma=0.1 ................................................
[CV] .................... C=0.1, gamma=0.1, score=0.659, total= 1.1min
[CV] C=0.1, gamma=0.1 ................................................
[CV] .

[Parallel(n_jobs=1)]: Done  20 out of  20 | elapsed: 70.7min finished


GridSearchCV(estimator=SVC(), param_grid={'C': [0.1, 1], 'gamma': [1, 0.1]},
             verbose=3)

#### <font color=#225e71>Keeping the best parameter combination for the algorithm</font>

In [53]:
grid.best_params_

{'C': 1, 'gamma': 0.1}

In [40]:
grid.best_estimator_

SVC(C=1, gamma=0.1)

In [54]:
grid_predictions = grid.predict(X_test)
grid_predictions

array([4, 4, 1, ..., 1, 2, 4], dtype=int64)

#### <font color=#225e71>Excecuting the Algorithm, this time with the proper values.</font>

In [64]:
my_model = SVC(kernel='linear', C=1.0, gamma=0.1)
my_model = my_model.fit(X_train, y_train )

In [67]:
my_model

SVC(gamma=0.1, kernel='linear')

In [69]:
support_vector_indices = my_model.support_
print(support_vector_indices)

[     4      5      6 ... 334204 334219 334226]


In [70]:
# Get number of support vectors per class
support_vectors_per_class = my_model.n_support_
print(support_vectors_per_class)

[58535 89596 59109 62764]


In [71]:
predictions = my_model.predict(X_test)

In [72]:
predictions

array([2, 4, 2, ..., 4, 2, 2], dtype=int64)

In [73]:
print('Confusion matrix:\n {}'.format(confusion_matrix(y_test, predictions)))
print('\n')
print('Classification report:\n {}'.format(classification_report(y_test, predictions)))
print('\n')
print('Model\'s accuracy:\n {}'.format(accuracy_score(y_test, predictions)))

Confusion matrix:
 [[13187  5830    22  1513]
 [ 7723 25355  1309  5685]
 [  593  3509  8918  6826]
 [ 2317  3481  4420 20722]]


Classification report:
               precision    recall  f1-score   support

           1       0.55      0.64      0.59     20552
           2       0.66      0.63      0.65     40072
           3       0.61      0.45      0.52     19846
           4       0.60      0.67      0.63     30940

    accuracy                           0.61    111410
   macro avg       0.61      0.60      0.60    111410
weighted avg       0.61      0.61      0.61    111410



Model's accuracy:
 0.6119917422134459



#### <font color=#225e71>It doesn’t perform well when we have large data set because the required training time is higher.     It also doesn’t perform very well, when the data set has more noise i.e. target classes are overlapping SVM doesn’t directly provide probability estimates, these are calculated using an expensive five-fold cross-validation.                             It is included in the related SVC method of Python scikit-learn library.</font>